### ISSUE TITLE
How to open Xmgrace WITHOUT Safe Mode using pygrace

### ISSUE THREAD

**Issue by Hira-Zaidi** [pygrace/pygrace#3]
Hello.I am writing a python script to plot graphs using xmgrace and pygrace. But I am unable to save those graphs using save func. of pygrace. The error is : saving is not allowed in safe mode......I know the command is" xmgrace -nosafe" ...When I wrote this in terminal it works .But I don't know how to use this command in pygrace source code or in my own script.So Please can any one tell me how to open xmgrace without safe mode .

**Comment by deanmalmgren** [comment]
Can you maybe create an example pygrace script that exhibits this problem? 

I'm not sure how/why `xmgrace -nosafe` is an issue. In order to save an `.agr` file with pygrace, you should just have to do something like:

``` python
grace.write_agr('my_filename.agr')
```

and it should write the actual `.agr` file as plain text without calling `xmgrace` at all. In fact, I think the only place where `xmgrace` is actually called is [in the write_file method](https://github.com/pygrace/pygrace/blob/master/PyGrace/grace.py#L166-L167), which uses the `gracebat` utility.

**Comment by Hira-Zaidi** [comment]
Thanx alot. It works
