### ISSUE TITLE
Transparency for filled areas

### ISSUE THREAD

**Issue by gpierris** [pygrace/pygrace#4]
Hello,

let me thank you first for taking the time to maintain PyGrace. I was wondering if it is possible to control the transparency of overlapping filled areas. For example below ![jointspace_0](https://f.cloud.github.com/assets/600726/1424345/2a3db06a-401c-11e3-8c90-d62935a7c996.png) I have two trajectories (mean values) surrounded by their 95% confidence interval, however, if I try to fill the area of the red one (using ElShadedArea) then it blocks the blue. I would expect either a fancy transparency like matplotlib/matlab packages, or at least when using patterns to fill the area the white gaps to be treated as transparent.

Are these possible in any way or not possible from Grace, hence impossible for PyGrace.

Thanks

**Comment by deanmalmgren** [comment]
Hey @gpierris, It turns out that this is a limitation with xmgrace and specifically its rendering engine motif (or lesstif, depending on your xmgrace version). Neither of these rendering engines, to the best of my knowledge, support transparency and so it doesn't work in xmgrace. Here are a couple of workaround ideas:
1. Export the resulting grace file to an eps or svg and modify the eps or svg directly to make the two 95% confidence interval layers transparent. I don't know the eps format as well as the svg, but this should work. My personal preference on this would be to export to svg and then use inkscape to manipulate the svg, but you can always just manipulate the svg file directly using the text editor of your choice.
2. I'm almost embarrassed to recommend this one because it is such a terrible hack, but you could always just create three different regions: one that is for the blue 95% confidence interval, one that is for the red 95% confidence interval, and one that is in the overlap between the two confidence intervals where you specify the color as if the two regions were transparent.
3. Use a different plotting library that uses a rendering engine that does support transparency, like matplotlib, for example.

Hope this helps! I'm going to close this issue because there isn't any obvious fix for pygrace here, but if you think of something else please feel free to reopen and keep the thread going!

**Comment by arulalant** [comment]
Thanks for your tips.
I written simple function calling "getOverlap" by using 2nd idea. 
https://gist.github.com/arulalant/b7a1cef170a2e25571f7

Here I posted blog with example plots with transparent lines.
https://tuxcoder.wordpress.com/2014/09/01/how-to-plot-transparent-lines-shades-in-xmgrace-uvcdat-pygrace/

Regards,
Arulalan.T
